# Generated by Django 3.0.4 on 2020-05-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
