# Generated by Django 3.0.4 on 2020-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emobno',
            field=models.IntegerField(default=1234567890),
        ),
    ]
