# Generated by Django 3.0.4 on 2020-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_employee_emobno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emobno',
            field=models.IntegerField(),
        ),
    ]
