# Generated by Django 3.0.4 on 2020-03-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_employee_phonnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emobno',
        ),
    ]
